[build]
  command = "eleventy"
  publish = "_site"
  functions = "functions"

[[redirects]]
  from = "/new"
  to = "/.netlify/functions/new"
  status = 200

[[redirects]]
  from = "/mypage/*"
  to = "/.netlify/functions/display?id=:splat"
  status = 302

[[redirects]]
  from = "/*"
  to = "/notfound.html"
  force = false
  status = 404